sudo: required
services:
    - docker

before_install:
    - docker build -t a1ku/docker-react-final:dev -f Dockerfile.dev .

script:
    - docker run -e CI=true a1ku/docker-react-final:dev npm run test -- --coverage