sudo: required
services:
    - docker

before_install:
    - docker build -t a1ku/docker-react-final:dev -f Dockerfile.dev .

script:
    - docker run -e CI=true a1ku/docker-react-final:dev npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react-final"
    env: "DockerReactFinal-env"
    bucket_name: "elasticbeanstalk-eu-west-1-906015301963"
    bucket_path: "docker-react-final"
    on:
        branch: master
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
